package io.dataease.enterprise.permission.domain;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import io.dataease.enterprise.permission.domain.PermissionDecision.*;
class PermissionDecisionTest {
    private final PermissionDecision engine = new PermissionDecision();
    private Rule rule(long id,String action,String effect,String scope,Long...schools){return new Rule(id,1,action,effect,scope,Set.of(schools));}
    private Binding role(long id,long school,Rule...rules){return new Binding("ROLE",id,id+100,Set.of(school),List.of(rules));}
    private Binding user(Rule...rules){return new Binding("USER",2,null,Set.of(),List.of(rules));}
    private Facts facts(String type,boolean member,boolean platform,List<Binding> bindings){return new Facts(1,2,1,1,3,1,type,"SCHOOL_COPY".equals(type)?20L:null,member,platform,Set.of(10L,20L),bindings);}
    @Test void rolesKeepSchoolPairsBeforeUnion(){var f=facts("DATASET",true,false,List.of(role(5,10,rule(1,"VIEW","ALLOW","ALL_ACTIVE_IN_TENANT")),role(6,20,rule(2,"VIEW","ALLOW","EXPLICIT",10L))));assertThat(engine.evaluate(f,"VIEW").allowedSchoolIds()).containsExactly("10");}
    @Test void personalAndOrganizationAdditionsDoNotReplaceRoleScope(){var f=facts("DATASET",true,false,List.of(role(5,10,rule(1,"VIEW","ALLOW","ASSIGNMENT")),new Binding("ORG",7,null,Set.of(),List.of(rule(2,"VIEW","ALLOW","EXPLICIT",20L)))));assertThat(engine.evaluate(f,"VIEW").allowedSchoolIds()).containsExactly("10","20");}
    @Test void matchingDeniesOnlySubtractTheirSchoolAndAction(){var f=facts("DATASET",true,false,List.of(user(rule(1,"VIEW","ALLOW","ALL_ACTIVE_IN_TENANT"),rule(2,"VIEW","DENY","EXPLICIT",20L),rule(3,"EXPORT","DENY","EXPLICIT",10L))));assertThat(engine.evaluate(f,"VIEW").allowedSchoolIds()).containsExactly("10");}
    @Test void exportAndDrillIntersectOrdinaryView(){var f=facts("DATASET",true,false,List.of(user(rule(1,"VIEW","ALLOW","EXPLICIT",10L),rule(2,"EXPORT","ALLOW","ALL_ACTIVE_IN_TENANT"),rule(3,"DRILL","ALLOW","EXPLICIT",20L))));assertThat(engine.evaluate(f,"EXPORT").allowedSchoolIds()).containsExactly("10");assertThat(engine.evaluate(f,"DRILL").authorizationAllowed()).isFalse();}
    @Test void resourceEditingRequiresSeparateViewAndNeverImpliesExport(){var f=facts("DASHBOARD",true,false,List.of(user(rule(1,"EDIT","ALLOW","NONE"))));assertThat(engine.evaluate(f,"EDIT").authorizationAllowed()).isFalse();f=facts("DASHBOARD",true,false,List.of(user(rule(1,"EDIT","ALLOW","NONE"),rule(2,"VIEW","ALLOW","NONE"))));assertThat(engine.evaluate(f,"EDIT").authorizationAllowed()).isTrue();assertThat(engine.evaluate(f,"EXPORT").authorizationAllowed()).isFalse();}
    @Test void platformExceptionIsViewOnlyAndDoesNotDependOnOrdinaryMembership(){var f=facts("DATASET",false,true,List.of(user(rule(1,"VIEW","DENY","ALL_ACTIVE_IN_TENANT"))));assertThat(engine.evaluate(f,"VIEW").allowedSchoolIds()).containsExactly("10","20");assertThat(engine.evaluate(f,"EXPORT").authorizationAllowed()).isFalse();}
    @Test void unknownAndUnavailableSchoolsNeverSurviveIntersection(){var f=facts("DATASET",true,false,List.of(new Binding("ROLE",5,9L,Set.of(10L,99L),List.of(rule(1,"VIEW","ALLOW","ASSIGNMENT"))),user(rule(2,"VIEW","ALLOW","EXPLICIT",99L))));assertThat(engine.evaluate(f,"VIEW").allowedSchoolIds()).containsExactly("10");}
    @Test void schoolCopyRequiresItsOwnSchoolAndView(){var f=facts("SCHOOL_COPY",true,false,List.of(role(5,10,rule(1,"VIEW","ALLOW","ASSIGNMENT")),user(rule(2,"EDIT","ALLOW","EXPLICIT",20L))));assertThat(engine.evaluate(f,"VIEW").authorizationAllowed()).isFalse();assertThat(engine.evaluate(f,"EDIT").authorizationAllowed()).isFalse();}
    @Test void factsAndSourcesAreDetachedImmutableSnapshots(){var schools=new HashSet<Long>(Set.of(10L));var r=new Rule(1,1,"VIEW","ALLOW","EXPLICIT",schools);schools.add(20L);assertThat(r.schools()).containsExactly(10L);assertThatThrownBy(()->r.schools().add(20L)).isInstanceOf(UnsupportedOperationException.class);var result=engine.evaluate(facts("DATASET",true,false,List.of(user(r))),"VIEW");assertThat(result.sources().getFirst().matchedSchoolIds()).containsExactly("10");}
    @Test void emptyAssignmentNoGrantAndInvalidActionsFailClosed(){assertThat(engine.evaluate(facts("DATASET",true,false,List.of(new Binding("ROLE",5,9L,Set.of(),List.of(rule(1,"VIEW","ALLOW","ALL_ACTIVE_IN_TENANT"))))),"VIEW").authorizationAllowed()).isFalse();assertThat(engine.evaluate(facts("DATASET",false,false,List.of()),"VIEW").authorizationAllowed()).isFalse();assertThatThrownBy(()->engine.evaluate(facts("DATASET",true,false,List.of()),"EDIT")).isInstanceOf(IllegalArgumentException.class);}
    @Test void excessiveSourceExpansionAndUnknownResourceKindsDenyEntireDecision(){var schools=new HashSet<Long>();for(long i=1;i<=5000;i++)schools.add(i);var binding=user(rule(1,"VIEW","ALLOW","ALL_ACTIVE_IN_TENANT"),rule(2,"VIEW","ALLOW","ALL_ACTIVE_IN_TENANT"),rule(3,"VIEW","ALLOW","ALL_ACTIVE_IN_TENANT"));var f=new Facts(1,2,1,1,3,1,"DATASET",null,true,false,schools,List.of(binding));var result=engine.evaluate(f,"VIEW");assertThat(result.authorizationAllowed()).isFalse();assertThat(result.reason()).isEqualTo("POLICY_FACT_BUDGET_EXCEEDED");assertThat(result.sources()).isEmpty();assertThat(engine.evaluate(facts("UNKNOWN",true,true,List.of()),"VIEW").authorizationAllowed()).isFalse();}
    @Test void platformOtherOperationsRequireMembershipAndExplicitActionWhileUsingActualView(){var rules=List.of(user(rule(1,"EXPORT","ALLOW","EXPLICIT",10L),rule(2,"VIEW","DENY","ALL_ACTIVE_IN_TENANT")));assertThat(engine.evaluate(facts("DATASET",false,true,rules),"EXPORT").authorizationAllowed()).isFalse();assertThat(engine.evaluate(facts("DATASET",true,true,rules),"EXPORT").allowedSchoolIds()).containsExactly("10");assertThat(engine.evaluate(facts("DATASET",true,true,List.of()),"EXPORT").authorizationAllowed()).isFalse();assertThat(engine.evaluate(facts("DATASET",true,true,List.of(user(rule(1,"EXPORT","ALLOW","EXPLICIT",10L),rule(2,"EXPORT","DENY","EXPLICIT",10L)))),"EXPORT").authorizationAllowed()).isFalse();}
}
